spring:
  application:
    name: app

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/productos_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/auditoria

server:
  port: 8080